### ISSUE TITLE
Watch(Event) should be be able to unmarshal to user-defined struct 

### ISSUE THREAD

**Issue by smartrevolution** [zabawaba99/firego#17] opened 2015-07-03 05:44 UTC
Hi,

I have a patch that makes it possible to Unmarshal the Data-field of an Event into a user-defined struct. 

The problem with the current implementation is, that the Data-Field always returns map[string]interface{} and it can happen, that i.e. numbers are unmarshaled in a way you would not expect. For example unix timestamps are returned as float64. Using Decoder.UseNumber is not enough to fix the problem.

Are you interested?

cheers
'(stefan)

**Comment by MrGossett** [comment] 2015-07-03 16:06
We always welcome pull requests 😀. I'd be interested to see how the API changes with your patch.

**Comment by smartrevolution** [comment] 2015-07-03 16:30
Just one tiny little parameter... ;)

Tim Gossett notifications@github.com schrieb am Fr., 3. Juli 2015 18:06:

**Comment by raulsntos** [comment] 2016-03-01 23:44
I've started using this recently and it seems it's still not possible to unmarshal to a defined struct, I get a `map[string]interface{}` but the problem is that I'm getting a result like this `{ID: {key1: data1, key2: data2}}` so in order to access the data I need to know the ID, I could use `range` for that but I think I should be getting `{key1: data1, key2: data2}` directly. At least, I think that's how it works with the Firebase Javascript API. Maybe I'm just missing something and this can be done already.

**Comment by zabawaba99** [comment] 2016-03-02 01:06
@raulsntos is it not possible to unmarshal to a struct of your choosing. I've been coming back to this issue every now and then but I'm not quiet sure how to approach this without breaking the API.

Regarding your issue in particular, can you provide some snippets of how you're using firego and the data that you're putting into firebase? I did some tests using curl and firego and they seem to be the same

**curl**

``` console
$ curl -L --header 'Accept: text/event-stream' -XGET "https://boiling-inferno-8978.firebaseio.com/demo.json"
event: put
data: {"path":"/","data":2}

event: put
data: {"path":"/","data":{"item":3}}

event: put
data: {"path":"/item","data":null}

event: put
data: {"path":"/","data":{"item":3}}

event: put
data: {"path":"/hello","data":"world"}

event: put
data: {"path":"/","data":{"item1":1,"item2":2,"item3":3}}

event: put
data: {"path":"/Something","data":{"AHHHH":true,"With":{"boom":"boom","nest":"values","pow":"OH MY!"}}}
```

**go output**

``` console
$ go run main.go
2016/03/01 19:56:04 New event: firego.Event{Type:"put", Path:"/", Data:2}
2016/03/01 19:56:44 New event: firego.Event{Type:"put", Path:"/", Data:map[string]interface {}{"item":3}}
2016/03/01 19:57:07 New event: firego.Event{Type:"put", Path:"/item", Data:interface {}(nil)}
2016/03/01 19:57:21 New event: firego.Event{Type:"put", Path:"/", Data:map[string]interface {}{"item":3}}
2016/03/01 19:57:28 New event: firego.Event{Type:"put", Path:"/hello", Data:"world"}
2016/03/01 19:58:07 New event: firego.Event{Type:"put", Path:"/", Data:map[string]interface {}{"item1":1, "item2":2, "item3":3}}
2016/03/01 20:00:34 New event: firego.Event{Type:"put", Path:"/Something", Data:map[string]interface {}{"AHHHH":true, "With":map[string]interface {}{"boom":"boom", "nest":"values", "pow":"OH MY!"}}}
```

**go source**

``` go
package main

import (
    "log"

    "github.com/zabawaba99/firego"
)

func main() {
    fb := firego.New("https://boiling-inferno-8978.firebaseio.com/demo", nil)

    events := make(chan firego.Event)
    if err := fb.Watch(events); err != nil {
        log.Fatal(err)
    }

    for event := range events {
        log.Printf("New event: %#v\n", event)
    }
}
```

**Comment by raulsntos** [comment] 2016-03-02 11:35
Sure, this is what I'm doing:
**main.go**

``` go
package main

import (
    "github.com/zabawaba99/firego"
    "log"
)

type Message struct {
    Sender string `json:"sender"`
    Text   string `json:"text"`
}

func NewMsg(sender string, text string) *Message {
    return &Message{sender, text}
}

var firebase *firego.Firebase

func main() {
    firebase = firego.New("https://test-raulsntos.firebaseio.com/chat", nil)

    SendMsg("Peter", "Hello World")
    SendMsg("Sarah", "How is it going?")

    ReceiveMsg()
}

func ReceiveMsg() {
    notifications := make(chan firego.Event)
    if err := firebase.Watch(notifications); err != nil {
        log.Fatal(err)
    }

    defer firebase.StopWatching()
    for event := range notifications {
        log.Println(event.Data)
    }
}

func SendMsg(sender string, text string) {
    if _, err := firebase.Push(NewMsg(sender, text)); err != nil {
        log.Fatal(err)
    }
}
```

**output**

```
C:\Users\raul-\gocode\src\github.com\raulsntos\chattest>go run main.go
2016/03/02 12:17:34 map[-KBr1qw6SI2R1d-amgYx:map[sender:Peter text:Hello World] -KBr1r427i8Xml90ZrdD:map[sender:Sarah text:How is it going?]]
```

**firebase dashboard**
![image](https://cloud.githubusercontent.com/assets/3903059/13459097/98d00562-e071-11e5-908e-d60588ba3a64.png)

Now if I run this javascript code:

``` javascript
var ref = new Firebase('https://test-raulsntos.firebaseio.com/chat');
ref.on('child_added', function(snapshot) {
    var message = snapshot.val();
    console.log(message)
});
```

I get this result:
![image](https://cloud.githubusercontent.com/assets/3903059/13459220/8e000ec4-e072-11e5-9623-4d6cda3af76f.png)
The difference is that in order to get the Objects that Javascript is showing on the console I would have to do something like this `event.Data.(map[string]interface{})["-KBr1r427i8Xml90ZrdD"]``but I don't know the ID and I don't want to, I just want to run the code each time for each Object like Javascript does.

**Comment by zabawaba99** [comment] 2016-03-02 13:40
Ah ok, I understand now. Unfortunately, I would say that that is the expected behavior of the `Watch` method. All is does it wrap the streaming API and give you the data you would get via SSE. A couple ways you might be able to work around this is 
- Listen to the `/chat` node first before any messages our sent. That way when you get a message, the ID will be in the `Path` of the event
- Iterate blindly through the `event.Data`. You know that it's going to be a `map[string]interface{}` where the `interface{}` is a map.

``` go
for event := range notifications {
    eventData, ok := event.Data.(map[string]interface{})
    if !ok {
        continue
    }

    for id, chat := range eventData {
        log.Printf("Id: %s", id)
        log.Printf("%#v\n", chat)
    }
}
```

---

That aside, I think it would be pretty neat to add some of the event listeners to `firego`. My only concern is that if we do that we would probably have to keep a connection open to firebase per listener registered, but that could just be a caveat until we find a better way.

**Comment by raulsntos** [comment] 2016-03-02 17:00
That's what I thought, ok then. It would be really nice to have the same features the Javascript API has, it seems the Streaming API is more limited. Thanks.

**Closed as completed** 2016-10-23 22:51 UTC
Labels: enhancement, help wanted
